local easy = {
	{
		question = "What is the atomic number of Magnesium (Mg)? ",
		answer = "b",
		a = "24",
		b = "12",
		c = "38",
		d = "36",
	},
	{
		question = "How do we determine the proton of a particular element with the use of a periodic table? Find the ____________ of the element in the periodic table. ",
		answer = "a",
		a = "atomic number",
		b = "atomic radius",
		c = "atomic mass",
		d = "atomic weight",
	},
	{
		question = "What is the number of neutron of the element Helium if its atomic number is two (2) and its atomic mass is four (4)? ",
		answer = "c",
		a = "0",
		b = "1",
		c = "2",
		d = "3",
	},
	{
		question = "What is the number of neutron of Ar? ",
		answer = "a",
		a = "22",
		b = "15",
		c = "23",
		d = "23",
	},
	{
		question = "What is the number of neutron of Mn? ",
		answer = "a",
		a = "30",
		b = "27",
		c = "32",
		d = "29",
	},
	{
		question = "What is the number of electron of Mn? ",
		answer = "d",
		a = "38",
		b = "21",
		c = "30",
		d = "25",
	},
	{
		question = "What is the number of electron of Mercury(Hg)? ",
		answer = "c",
		a = "75",
		b = "69",
		c = "80",
		d = "82",
	},
	{
		question = "What is the number of neutron of Fr? ",
		answer = "a",
		a = "223",
		b = "233",
		c = "213",
		d = "243",
	},
	{
		question = "What is the number of proton of Fr? ",
		answer = "b",
		a = "67",
		b = "87",
		c = "77",
		d = "96",
	},
	{
		question = "What is the number of proton of Polonium(Po)? ",
		answer = "b",
		a = "34",
		b = "84",
		c = "54",
		d = "64",
	},
	{
		question = "What is the number of proton of La? ",
		answer = "b",
		a = "37",
		b = "57",
		c = "67",
		d = "87",
	},
	{
		question = "What is the number of neutron of Hg? ",
		answer = "c",
		a = "117",
		b = "125",
		c = "115",
		d = "105",
	},
	{
		question = "What is the number of neutron of Thulium(Tm)? ",
		answer = "d",
		a = "117",
		b = "110",
		c = "105",
		d = "100",
	},
	{
		question = "What is the element name of the symbol Rn? ",
		answer = "a",
		a = "Radon",
		b = "Argon",
		c = "Boron",
		d = "Bromine",
	},
	{
		question = "What is the element name of the symbol Cs? ",
		answer = "a",
		a = "Cesium",
		b = "Calcium",
		c = "Sulfur",
		d = "Copper",
	},
	{
		question = "What is the symbol of the element Copper? ",
		answer = "a",
		a = "Cu",
		b = "Cr",
		c = "Cp",
		d = "Co",
	},
	{
		question = "What is the atomic number of Cu? ",
		answer = "b",
		a = "24",
		b = "29",
		c = "26",
		d = "27",
	},
	{
		question = "What is the atomic number of Iron? ",
		answer = "a",
		a = "26",
		b = "28",
		c = "30",
		d = "32",
	},
	{
		question = "What is the mass number of Argon? ",
		answer = "c",
		a = "70",
		b = "30",
		c = "40",
		d = "50",
	},
	{
		question = "What is the mass number of Tin? ",
		answer = "d",
		a = "112",
		b = "110",
		c = "115",
		d = "119",
	},
	{
		question = "What is the mass number of Silver? ",
		answer = "d",
		a = "110",
		b = "109",
		c = "105",
		d = "108",
	},
	{
		question = "What is the number of neutron of Silver? ",
		answer = "b",
		a = "51",
		b = "61",
		c = "11",
		d = "31",
	},
	{
		question = "What is the atomic number of Aluminum? ",
		answer = "a",
		a = "13",
		b = "15",
		c = "10",
		d = "17",
	},
	{
		question = "What is the mass number of Krypton? ",
		answer = "a",
		a = "86",
		b = "78",
		c = "76",
		d = "65",
	},
	{
		question = "What is the atomic number of Krypton? ",
		answer = "d",
		a = "75",
		b = "68",
		c = "56",
		d = "36",
	},
	{
		question = "What is the number of neutrons of the element Argon if its atomic number is 18 and its atomic mass is 40? ",
		answer = "a",
		a = "22",
		b = "16",
		c = "20",
		d = "15",
	},
	{
		question = "What is the Symbol of the Element Lanthanum? ",
		answer = "b",
		a = "Ln",
		b = "La",
		c = "Lt",
		d = "Lm",
	},
	{
		question = "What is the name of the Symbol Fr? ",
		answer = "c",
		a = "Froncium",
		b = "Polonium",
		c = "Francium",
		d = "Thulium",
	},
	{
		question = "What is the Atomic Number of Tin? ",
		answer = "a",
		a = "50",
		b = "60",
		c = "55",
		d = "80",
	},
	{
		question = "What is the Mass Number of Neon? ",
		answer = "d",
		a = "32",
		b = "56",
		c = "39",
		d = "30",
	},
}

return easy
