local hard = {
	{
		question = "What will most likely happen to a metallic atom after ionic bonding? ",
		answer = "b",
		info = "Did you know that Ionic bonding results in compounds known as ionic, or electrovalent, compounds, which are best exemplified by the compounds formed between nonmetals and the alkali and alkaline-earth metals.",
		a = "It forms anion and became unstable.",
		b = "It forms cation and become stable",
		c = "It forms anion and became stable.",
		d = "It becomes cation and became unstable.",
	},
	{
		question = "Element Li belongs to Group 1. Which of the following describes element Li?",
		answer = "a",
		info = "Did you know that The electronegativity scale of the elements compares the ability of the atoms of the various elements to attract electrons to themselves?",
		a = "Low electronegativity",
		b = "High electronegativity",
		c = "High ionization energy",
		d = "A non-metallic element",
	},
	{
		question = "It is the kind of bond that results when two identical non-metallic atoms combine.",
		answer = "Non-polar covalent bond",
		info = "Did you know that Covalent bond, in chemistry, the interatomic linkage that results from the sharing of an electron pair between two atoms. The binding arises from the electrostatic attraction of their nuclei for the same electrons.?",
		identification = true
	},
	{
		question = "Why do atoms combine to form compound?",
		answer = "c",
		info = "Did you know that Chemical compound, any substance composed of identical molecules consisting of atoms of two or more chemical elements?",
		a = "To form compound",
		b = "To form molecules",
		c = "To attain stability",
		d = "To produce ions",
	},
	{
		question = "It is the bond that holds the atoms of the elements in Group 1 and 2 of the Periodic Table.",
		answer = "Metallic bond",
		info = "Did you know that = Metallic bond, force that holds atoms together in a metallic substance. Such a solid consists of closely packed atoms. In most cases, the outermost electron shell of each of the metal atoms overlaps with a large number of neighbouring atoms?",
		identification = true
	},
	{
		question = "It is the kind of particles produce after covalent bonding. ",
		answer = "b",
		info = "Did you know that Molecule, a group of two or more atoms that form the smallest identifiable unit into which a pure substance can be divided and still retain the composition and chemical properties of that substance.",
		a = "Electron",
		b = "Molecule",
		c = "Atom",
		d = "Ion",
	},
	{
		question = "Which among the following compounds forms a polar covalent bond?",
		answer = "d",
		info = "Did you know that An ionic bond is actually the extreme case of a polar covalent bond, the latter resulting from unequal sharing of electrons rather than complete electron transfer.",
		a = "H2",
		b = "CaO",
		c = "MgCl2",
		d = "H2O",
	},
	{
		question = "Which properties of the atoms is most suitable reference for the kind of bond that will take place between/among them?",
		answer = "a",
		info = "Did you know that Electronegativity, in chemistry, the ability of an atom to attract to itself an electron pair shared with another atom in a chemical bond.",
		a = "Electronegativity",
		b = "Ionization energy",
		c = "Atomic Size",
		d = "Electron Affinity",
	},
	{
		question = "Which of the following solute will make water a good conductor of electricity?",
		answer = "c",
		info = "Did you know that In a conductor, the valence band is partially filled, and since there are numerous empty levels, the electrons are free to move under the influence of an electric field; thus, in a metal the valence band is also the conduction band.",
		a = "Wax",
		b = "Sugar",
		c = "Vetsin",
		d = "Oil",
	},
	{
		question = "From the list of elements, choose 2 that would likely form an ionic bond: Si, F, Ne, Li",
		answer = "d",
		info = "Did you know that Ionic bonding results in compounds known as ionic, or electrovalent, compounds, which are best exemplified by the compounds formed between nonmetals and the alkali and alkaline-earth metals.",
		a = "Si and F",
		b = "Ne and Si",
		c = "Li and S",
		d = "Li and F",
	},
	{
		question = "How many non-polar covalent bond will there be in N2 molecule?",
		answer = "c",
		info = "Did you know that A non-polar covalent bond is a type of chemical bond that is formed when electrons are shared equally between two atoms. Thus, in an atom, the number of electrons shared by the adjacent atoms will be the same.",
		a = "1",
		b = "2",
		c = "3",
		d = "4",
	},
	{
		question = "How is the bond in Br2 different from MgF2?",
		answer = "a",
		info = "Did you know that Ionic bond, also called electrovalent bond, type of linkage formed from the electrostatic attraction between oppositely charged ions in a chemical compound.",
		a = "MgF2 is ionic bond while Br 2 is covalent bond.",
		b = "MgF2 is covalent bond while Br 2 is ionic bond.",
		c = "MgF2 is metallic bond while Br 2 is covalent bond.",
		d = "MgF2 is ionic bond while Br 2 is metallic bond.",
	},
	{
		question = "If you are going to make a list of all the needed ingredients in cooking and you are tasked to write the chemical formula for some condiments that are ionic compounds, then what will be the correct formula for table salt?",
		answer = "d",
		info = "Did you know that Ionic compounds are neutral compounds made up of positively charged ions called cations and negatively charged ions called anions. For binary ionic compounds (ionic compounds that contain only two types of elements), the compounds are named by writing the name of the cation first followed by the name of the anion.",
		a = "SClO2",
		b = "SCl2",
		c = "Na4C",
		d = "NaCl",
	},
	{
		question = "When does covalent bonding takes place?",
		answer = "c",
		info = "Did you know that A covalent bond forms when the bonded atoms have a lower total energy than that of widely separated atoms.",
		a = "It takes place when atoms transfer electrons.",
		b = "It takes place when atoms attain stability.",
		c = "It takes place when atoms share electrons.",
		d = "It takes place when the attraction is strong.",
	},
	{
		question = "Which among the following shows that an atom is stable?",
		answer = "d",
		info = "Did you know that Atoms found in nature are either stable or unstable. An atom is stable if the forces among the particles that makeup the nucleus are balanced.",
		a = "Having 2 valence electrons",
		b = "Having 6 valence electrons",
		c = "Having 4 valence electrons",
		d = "Having 8 valence electrons",
	},
	{
		question = "It refers to the tendency of an atom to pull or remove one or more electrons from a neutral atom.",
		answer = "Electron Affinity",
		info = "Did you know that Electron affinity is the energy change that results from adding an electron to a gaseous atom. For example, when a fluorine atom in the gaseous state gains an electron to form F⁻(g), the associated energy change is -328 kJ/mol.",
		identification = true
	},
	{
		question = "Which among the following compounds has high melting and boiling point?",
		answer = "d",
		info = "Did you know that Ionic compound can be defined as the crystalline solids are formed by neatly packed ions of opposite charge. Ionic compounds are usually formed when metals react with non-metals.",
		a = "Metallic compound",
		b = "Covalent compound",
		c = "Non-metallic compound",
		d = "Ionic compound",
	},
	{
		question = "Which among the following is not a property of a metallic compound?",
		answer = "a",
		info = "Did you know that A metallic compound is a compound that contains one or more metal elements bonded to another element. Typically, the metal atom acts as the cation in the compound and is bonded to a nonmetallic anion or an ionic oe.",
		a = "Low melting point",
		b = "Luster",
		c = "Good conductor of heat",
		d = "Malleability",
	},
	{
		question = "Which of the following pair of compounds is an ionic compound and covalent compound, respectively?",
		answer = "c",
		info = "Did you know that Ionic compounds are (usually) formed when a metal reacts with a nonmetal (or a polyatomic ion) while, covalent compounds are formed when two nonmetals react with each other.",
		a = "water; salt",
		b = "paraffin wax; carbon dioxide",
		c = "magnesium chloride; hydrogen dioxide",
		d = "magnesium chloride; potassium oxide",
	},
	{
		question = "Which of the following states the difference between a polar covalent bond and a nonpolar covalent bond?",
		answer = "d",
		info = "Did you know that If two atoms have an electronegativity difference of 0.4 or less, they form a non-polar covalent bond while if two atoms have an electronegativity difference between 0.4 and 1.8, they form a polar covalent bond.",
		a = "Polar covalent bond formed between metals and nonmetals;nonpolar covalent bond forms between nonmetals.",
		b = "Polar covalent bond formed between nonmetals; nonpolar covalent bond forms between metal and nonmetals.",
		c = "Polar covalent bond formed between the same nonmetals and nonmetals; nonpolar covalent bond is between different nonmetals.",
		d = "Polar covalent bond formed between the different nonmetals; nonpolar covalent bond forms between the same nonmetals.",
	},
	{
		question = "This is a bond that results when two identical non-metallic atoms combine.",
		answer = "Non-polar covalent bond",
		info = "Did you know that A non-polar covalent bond is a bond in which the electron pair is shared equally between the two bonded atoms. One example is hydrogen gas, H2. The two hydrogen atoms are identical, so the bond between them is non-polar.",
		identification = true
	},
	{
		question = "The bond that holds the atoms of the group 1 and group 2 elements of the periodic table.",
		answer = "Metallic bond",
		info = "Did you know that Metallic bonds occur among metal atoms. Whereas ionic bonds join metals to non-metals, metallic bonding joins a bulk of metal atoms. A sheet of aluminum foil and a copper wire are both places where you can see metallic bonding in action.",
		identification = true
	},
	{
		question = "What kind of particles produces after covalent bonding?",
		answer = "Molecule",
		info = "Did you know that A molecule is two or more atoms connected by chemical bonds, which form the smallest unit of a substance that retains the composition and properties of that substance. Molecules form the basis of chemistry. Molecules are noted with the element symbol and a subscript with the number of atoms.",
		identification = true
	},
	{
		question = "In the modern periodic table, elements are arranged according to increasing ______________.",
		answer = "a",
		info = "Did you know that Elements are arranged according to their atomic number. The atomic number of an element is equal to its number of protons, being an entire number.",
		a = "Atomic Number",
		b = "Atomic Mass",
		c = "Date of Discovery",
		d = "Electrical Conductivity",
	},
	{
		question = "Which of the following elements is non-metal?",
		answer = "c",
		info = "Did you know that Carbon is located in the right hand side of the periodic table and has none of the properties of metals like high conductivity, ductility and malleability.",
		a = "Aluminum",
		b = "Gold",
		c = "Carbon",
		d = "Tin",
	},
	{
		question = "Which element shown here is the least metallic?",
		answer = "a",
		info = "Did you know that Zinc is the less metallic element among this four, as is closer to the non-metals in the periodic table.",
		a = "Zinc",
		b = "Iron",
		c = "Cadmium",
		d = "Silver",
	},
	{
		question = "Which of the following elements is metalloid?",
		answer = "b",
		info = "Did you know that Silicon has properties that are between those of metals and non-metals (metalloid). Metalloids can be distinguished in a periodic table as they are forming a diagonal between the metals and the non-metals.",
		a = "Oxygen",
		b = "Silicon",
		c = "Chlorine",
		d = "Argon",
	},
	{
		question = "Which of the following is a noble gas? ",
		answer = "d",
		info = "Did you know that Noble gases are simple elements not molecules thus carbon dioxide cannot be a noble gas as is a molecule not an element. Noble gases are located in group 18 at the left hand side of the periodic table and the first of the noble gases is Helium.",
		a = "Carbon Dioxide ",
		b = "Boron",
		c = "Oxygen",
		d = "Helium",
	},
	{
		question = "In the periodic table, the most active nonmetals will be found in the: ",
		answer = "a",
		info = "Did you know that The reactivity of the non-metals increase according to their electronegativity, thus being the nonmetal elements on the upper right of the table the ones more reactive. Check the electronegativity trends for the elements to have a clear view of their reactivity.",
		a = "Upper Right",
		b = "Upper Left ",
		c = "Lower Right",
		d = "Lower Left",
	},
	{
		question = "Which of these elements on the periodic table has the highest electronegativity? ",
		answer = "b",
		info = "Did you know that Fluorine is the element in the periodic table that has the highest electronegativity according to Pauling scale. You can easily find this using a periodic table understanding what the trends in electronegativity for the elements that are in the same group or period.",
		a = "Lithium",
		b = "Fluorine",
		c = "Rubidium",
		d = "Iodine",
	},
	{
		question = "Neon is an example of a(n):",
		answer = "b",
		info = "Did you know that The name neon is derived from the Greek word neos, “new.” Neon was discovered (1898) by the British chemists Sir William Ramsay and Morris W. Travers as a component of the most volatile fraction of liquefied crude argon obtained from air.",
		a = "Alkali Metal",
		b = "Noble Gas",
		c = "Halogen",
		d = "Rare Earth Metal",
	},
	{
		question = "How many valence or outer level electrons does an atom of the element argon",
		answer = "8 valence electrons",
		info = "Did you know that Valence, also spelled valency, in chemistry, the property of an element that determines the number of other atoms with which an atom of the element can combine.",
		identification = true
	},
	{
		question = "What does two elements chemically bonded form?",
		answer = "b",
		info = "Did you know that Compounds can be defined as substances consisting of 2 or more different types of elements in a fixed ratio of their atoms. When the elements combine, some individual property of the elements is lost and the newly formed compound has new properties.",
		a = "Element",
		b = "Compound",
		c = "Mixture",
		d = "Solutions",
	},
	{
		question = "Elements are represented by chemical symbol.  Symbols are written with?",
		answer = "d",
		info = "Did you know that Chemical symbol, short notation derived from the scientific name of a chemical element. The present chemical symbols express the systematizing of chemistry by the atomic theory of matter.",
		a = "all lower case letters",
		b = "all capital letters",
		c = "always only one  letter",
		d = "At least and ONLY one capital letter",
	},
	{
		question = "An element that has two valence or outer level electrons would be considered a(n):",
		answer = "d",
		info = "Did you know that Metal, any of a class of substances characterized by high electrical and thermal conductivity as well as by malleability, ductility, and high reflectivity of light.",
		a = "Nonmetal ",
		b = "Noble Gas",
		c = "Halogen",
		d = "Metal",
	},
	{
		question = "Sodium is in the same group or family as:",
		answer = "a",
		info = "Did you know that Sodium (Na), chemical element of the alkali metal group (Group 1 [Ia]) of the periodic table. Sodium is a very soft silvery-white metal.",
		a = "Lithium",
		b = "Helium",
		c = "Calcium",
		d = "Thorium",
	},
	{
		question = "Iodine is an example of a(n):",
		answer = "b",
		info = "Did you know that Halogen, any of the six nonmetallic elements that constitute Group 17 (Group VIIa) of the periodic table. They were given the name halogen, from the Greek roots hal- (“salt”) and -gen (“to produce”), because they all produce sodium salts of similar properties, of which sodium chloride—table salt, or halite—is best known.",
		a = "Noble Gas",
		b = "Halogen",
		c = "Alkali Metal",
		d = "Rare Earth Metal",
	},
	{
		question = "If an element has one to three valence or outer level electrons, then it is a(n):",
		answer = "d",
		info = "Did you know that The electrons on the outermost energy level of the atom are called valence electrons. Valence electrons are involved in bonding one atom to another.The attraction of each atom’s nucleus for the valence electrons of the other atom pulls the atoms together.",
		a = "Nonmetal",
		b = "Halogen",
		c = "Noble Gas",
		d = "Metal",
	},
	{
		question = "Which of the following elements belongs to the group that includes the most active metals?",
		answer = "b",
		info = "Did you know that Active metals are characterized by their tendency to readily combine with gaseous oxygen and atmospheric water vapor due to a single electron in its outer shell that can be readily exchanged to form a cation and ultimately lead to a chemical reaction.",
		a = "Aluminum",
		b = "Sodium",
		c = "Iron",
		d = "Mercury",
	},
	{
		question = "The family in the periodic table that contains the most reactive metals is the_______.",
		answer = "c",
		info = "Did you know that The alkali metals are so called because reaction with water forms alkalies (i.e., strong bases capable of neutralizing acids). The alkali metals are so reactive that they are generally found in nature combined with other elements.",
		a = "Alkaline Earth Metals",
		b = "Transition Metals ",
		c = "Alkali Metals",
		d = "Other Metals",
	},
	{
		question = "The atomic number of Nickel is?",
		answer = "a",
		info = "Did you know that Nickel has high electrical and thermal conductivity. More than half the nickel produced is used in alloys with iron (particularly in stainless steels), and most of the rest is used in corrosion-resistant alloys with copper (including Monel, which contains some 60 to 70 percent nickel, 30 to 40 percent copper, and small amounts of other metals such as iron) and in heat-resistant alloys with chromium.",
		a = "28",
		b = "58.6934",
		c = "Ni",
		d = "Nickel",
	},
	{
		question = "Non-metals and metalloids are the Elements which are considered semiconductors.",
		answer = true,
		info = "Did you know that Semiconductors are the materials which have a conductivity between conductors (generally metals) and non-conductors or insulators (such as ceramics). Semiconductors can be compounds such as gallium arsenide or pure elements, such as germanium or silicon.",
        true_or_false = true
	},
	{
		question = "Dmitri Mendelive is the first person who arranged the periodic table.",
		answer = false,
		info = "Did you know that Dmitri Mendeleev, a Russian chemist and teacher, devised the periodic table — a comprehensive system for classifying the chemical elements. Mendeleev was born in 1834 in the far west of Russia’s Siberia, the youngest of a dozen or more children (reports vary).",
        true_or_false = true
	},
	{
		question = "Atomic Weight is the property that Mendeleev use to order his periodic table.",
		answer = true,
		info = "Did you know that Atomic weight, also called relative atomic mass, ratio of the average mass of a chemical element’s atoms to some standard. Since 1961 the standard unit of atomic mass has been one-twelfth the mass of an atom of the isotope carbon-12.",
        true_or_false = true
	},
	{
		question = "The element that Mendeleev predicts is Gallium.",
		answer = true,
		info = "Did you know that Gallium does not occur free or concentrated in independent minerals, except for gallite, CuGaS2, rare and economically insignificant. It is extracted as a by-product from zinc blende, iron pyrites, bauxite, and germanite.",
        true_or_false = true
	},
	{
		question = "Each row in the periodic table is called a cluster.",
		answer = false,
		info = "Did you know that The horizontal rows of the periodic table are called periods. Each period corresponds to the successive occupation of the orbitals in a valence shell of the atom, with the long periods corresponding to the occupation of the orbitals of a d subshell.",
        true_or_false = true
	},
	{
		question = "Each column in the periodic table is called a group.",
		answer = true,
		info = "Did you know that The columns of the periodic table, which contain elements that show a family resemblance, are called groups. All members of a particular group have analogous outermost (valence) electron configurations, suggesting that all members of a group should show a family relationship in the types and numbers of the chemical bonds that they are able to form.",
        true_or_false = true
	},
	{
		question = "Group in the periodic table that these elements belong: La, Ce, Er etc...",
		answer = "Lanthanide",
		info = "Did you know that All of the lanthanide elements are silver-colored, reactive solid metals that tarnish in air?",
		identification = true
	},
	{
		question = "How many electrons are being shared between the two carbon atoms in the compound ethyne? Ethyne has the Lewis structure: H−C≡C−H",
		answer = "6",
		info = "Did you know that The simplest alkyne, it is explosive if mixed with air. When burned with oxygen, it produces extremely high temperatures up to 3480°C (6300°F) and is used in oxyacetylene torches. It is polymerized to manufacture plastics, synthetic fibres, resins and neoprene. It is used to produce ethanal and ethanoic acid.",
		identification = true
	},
	{
		question = "What group does H(Hydrogen) Belong?",
		answer = "Nonmetal",
		info = "Did you know that Even counting the halogens and the noble gases there are only 18 elements in the periodic table that are considered nonmetals.",
		identification = true
	},
	{
		question = "Give one element belong to the Metalloid Group. (Symbol/s only)",
		answer = {
			"B",
			"Si",
			"Ge",
			"As",
			"Sb",
			"Te",
		},
		info = "Did you know that The most abundant metalloid in Earth's crust is silicon, which is the second most abundant element overall (oxygen is most abundant).",
		identification = true
	},
	{
		question = "The bond between sulfur (electronegativity value 2.5) and chlorine (electronegativity value 3.0) would be:",
		answer = "Polar Covalent",
		info = "Did you know that If the electronegativity difference between the two atoms is between 0.5 and 2.0, the atoms form a polar covalent bond. Polar Covalent Electronegativity Values are Not Identical.",
		identification = true
	},
	{
		question = "The electrons in a nonpolar covalent bond are:",
		answer = "Shared Equally",
		info = "Best example of it would be the bond between two hydrogen atoms to form hydrogen gas.",
		identification = true
	},
	{
		question = "Group in the periodic table that these elements belong: Rh, Os, Db, Cn etc...",
		answer = "Transition Metal",
		info = "Did you know that Transition metals are generally good conductors of heat and electricity, malleable and ductile. Their compounds are often brightly colored in solution and when hydrated, and can exhibit multiple positive oxidation states. They are hard solids, with high melting points and boiling points. Their compounds are often paramagnetic. They are usually quite dense, and are less reactive than a alkali or alkaline earth elements. They are often good catalysts, and readily form complexes with molecules called ligands.",
		identification = true
	},
	{
		question = "Group in the periodic table that these elements belong: Lr, Am, Md, No etc...",
		answer = "Actinide",
		info = "Did you know that Actinides have the ability to undergo nuclear reactions.",
		identification = true
	},
}

return hard
